apiVersion: v1
kind: Service
metadata:
  name: api-service-test
  namespace: mi-production-tracker-keycloak
  labels:
    app: keycloak
spec:
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 8080
  selector:
    app: keycloak
  type: ClusterIP
