apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keycloak-ingress
  namespace: mi-production-tracker-keycloak
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: www.gentar.org
      http:
        paths:
          - path: /keycloak(/|$)(.*)
            pathType: Prefix
            backend:
              serviceName: keycloak
              servicePort: 9090
  tls:
    - hosts:
        - gentar.org
        - www.gentar.org
      secretName: gentar-tls
