apiVersion: v1
kind: ServiceAccount
metadata:
  name: mi-production-tracker-keycloak-deployment
  namespace: mi-production-tracker-keycloak
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: mi-production-tracker-keycloak-deployment-access
  namespace: mi-production-tracker-keycloak
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - replicasets
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups:
      - "extensions"
    resources:
      - deployments
      - replicasets
      - ingresses
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: mi-production-tracker-keycloak-deployment-access-binding
  namespace: mi-production-tracker-keycloak
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mi-production-tracker-keycloak-deployment-access
subjects:
  - kind: ServiceAccount
    name: mi-production-tracker-keycloak-deployment
    namespace: mi-production-tracker-keycloak
