version: '3.7'
services:

  prod_tracker:
    #image: rwilsonebi/impc_prod_tracker:1.0
    build: ./impc_prod_tracker
    environment:
      - TRACKER_PORT=8901
    restart: always
    expose:
      - 8901
    ports:
      - "127.0.0.1:8901:8901"
    networks:
      production:

  keycloak:
    container_name: keycloak-gentar
    image: quay.io/keycloak/keycloak:25.0.0
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_USERNAME: keycloak_admin
      KC_DB_PASSWORD: keycloak_admin
    command:
      - "start-dev"
    depends_on:
      - postgres
    networks:
      - production

  postgres:
    container_name: postgres-keycloak
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "6000:5432"  # Mapping PostgreSQL port 5432 inside container to port 6000 on host
    networks:
      - production


networks:
  production:
