= GenTaR REST API
{date}
:doctype: book
:icons: font
:source-highlighter: highlightjs
:highlightjs-theme: github
:toc: left
:toclevels: 3
:sectlinks:
:sectnums:

[introduction]
== Introduction

GenTaR is designed to coordinate the production of transgenic mice between high-throughput
mouse production facilities and consortia of clinicians and human geneticists while
minimizing the overlap and maximizing efficiencies. GenTaR captures the intention of a
consortium to produce mutant mice targeting a particular gene, and the progress of
mouse production. It records information about the mutation created, and tracks the
state of phenotyping performed on the mutant mouse line.

This is a secure resource that can house various types of mutations linked to genes,
and will provide different data access policies to users.

This guide is aimed at developers of such applications.

== Usage of HTTP Verbs

The following table describes how the GenTaR API interprets the HTTP verbs.

.HTTP Verbs
|===
|HTTP Verb | Usage

|GET
|GET is used to retrieve information without changing the state of the system.

|POST
|POST is used to submit an entity to the specified resource, often causing a change in state or side effects on the system.

|PUT
|PUT method replaces all current representations of the target resource with the request payload.

|===

Other verbs, such as DELETE, are not supported by GenTaR at present.

== Pagination and Sorting
Most of the endpoints returning collections are paginated and can be sorted. If no parameters are
specified, then the default ones are applied.

=== Pagination
The parameters to specify the pagination are:
|===
|Parameter | Description
|page
|Number of the page to retrieve. It starts with 0 (which is the default value).
|size
|Number of elements to retrieve.

|===

=== Sorting
The parameters to specify the sorting are:
|===
|Parameter | Description
|sort
|Column and direction to sort, separated by comma. The directions are ASC or DESC.
Example: sort=tpn,ASC

|===

For example, to get the first 15 projects in the system, ordered by tpn, the call to the enpoint
would be:

 api/projects?page=0&size=15&sort=tpn,ASC

== Authentication
anchor:login[]

After a user is registered in the system (see: <<Create a user>>), they can start working with GenTaR.

The first step begins with logging into GenTaR using the /auth/signin endpoint.
The user issues a POST request to the endpoint and supplies the username and the password
credentials specified at registration as the JSON request payload (see the <<Login Data Structure>> example below).
A JSON Web Token (see https://jwt.io) is returned if the login is successful.

In all subsequent interactions with GenTaR the user provides the access token to authenticate each request to a protected route or resource.
The tokens are signed by the server so the server can validate the signature of the token to grant the access to resources.
The access token is a Base64 encoded String, that should be included as an Authorization HTTP header like this:

 Authorization: Bearer eyJhbGciOiJSUzI1NiJIUzI1NiJ9.eyJpc3MiOiJjb2RlcmFkYXIiLCJleHAiOjE0ODQ1MTUzOTUsInR5cGUiOiJSRUZSRVNIIiwiaWF0IjoxNDg0NTE1NDU1LCJ1c2VySWQiOiIxIiwidXNlcm5hbWUiOiJyYWRhciJ9.zfkyc5jkPiAUEt7nU25SJxKprcPiXaiq0Q6bCJ_RrQo

The access token is short-lived and by default expires after 30 minutes.

A typical work flow follows this pattern:

. Client logs in with username and password to obtain a token
. Client interacts with resources in GenTaR by providing the access token in each request
. After 30 minutes client gets a 401-Response
. Clients logs in again and retrieves a new token to continue working with the system

See more:

* https://auth0.com/docs/tokens/refresh-token
* https://auth0.com/blog/refresh-tokens-what-are-they-and-when-to-use-them/


=== POST
==== Successful authentication

===== Login Data Structure
include::{snippets}/auth/signin/request-fields.adoc[]

===== Example Request
include::{snippets}/auth/signin/http-request.adoc[]

===== Example Response
include::{snippets}/auth/signin/http-response.adoc[]

===== Response Structure
include::{snippets}/auth/signin/response-fields.adoc[]

==== Error in authentication: user/password is incorrect
When trying to sign in with an incorrect user or password the system will return
an error message.

.request
include::{snippets}/auth/signin/no-valid-user-password/http-request.adoc[]

.response
include::{snippets}/auth/signin/no-valid-user-password/http-response.adoc[]



== Users
anchor:users[]
This section describes the REST endpoints to manage users in the system.


=== Fields
These are the fields you are going to see in the body of a request in a GET or in the payload for POST or PUT
operations.

include::{snippets}/people/getPerson/response-fields.adoc[]

=== GET

==== Get Current Logged Person

Get the current user information. The current user is the owner of the token used in the request.

===== Example Request

Curl:
include::{snippets}/people/getPerson/curl-request.adoc[]

===== Example Response

include::{snippets}/people/getPerson/http-response.adoc[]


=== POST

==== Create a user

To create a user in the system specify the user in a JSON document that sent to the following endpoint.

===== Example Request

Curl:
include::{snippets}/people/postPerson/curl-request.adoc[]

===== Example Response

include::{snippets}/people/postPerson/http-response.adoc[]


==== Request password reset

An example of how to request a password reset for a specific user is shown below.
When this endpoint is used, the user will receive an email with a link and a secret pin. By following the
link and using the secret pin the user can set a new password.

===== Example Request

Curl:
include::{snippets}/people/requestPasswordReset/curl-request.adoc[]

===== Example Response

include::{snippets}/people/requestPasswordReset/http-response.adoc[]

=== PUT

==== Update a managed user

This endpoint allows a manager to update some information for a user that is managed by them.

===== Example Request

Curl:
include::{snippets}/people/updateManagedUser/curl-request.adoc[]

===== Example Response

include::{snippets}/people/updateManagedUser/http-response.adoc[]

==== Update own user

This endpoint allows a user that is currently logged in the system to modify data like the
name, password of whether they are contactable or not.

If a user wants to update their password, it's necessary to provide the current password
('currentPassword' field) and the new password ('newPassword' field). Otherwise, the fields can be
null or simply be omitted in the request.

===== Example Request

Curl:
include::{snippets}/people/updateOwnUser/curl-request.adoc[]

===== Example Response

include::{snippets}/people/updateOwnUser/http-response.adoc[]



== Projects
anchor:chapter-configure[]
This section describes the REST endpoints for projects in the system.

A project in GenTaR is a top level object. It specifies an intention,
and it is associated with one or more plans that contain information
about production attempts, or the state of phenotyping.

=== Fields
These are the fields you are going to see in the body of a request in a GET or in the payload for POST or PUT
operations.
include::{snippets}/projects/getProject/response-fields.adoc[]

[#_project_filters]
=== Filters
When you use request all projects, see the section <<Get all Projects>>, you can use filters on the result to select the information you require.

Filters are applied by appending the filter to the endpoint in the following fashion

 /api/projects?<filter name>=<value to use as the filter>

*Note:* the names of the filters are case sensitive.

Filter values can be supplied as a comma separated list

For example, you could use this request to obtain information about the projects
with the identifiers TPN:000000001 and TPN:000000004

 /api/projects?tpn=TPN:000000001,TPN:000000004

You can also combine filters in the following fashion

 /api/projects?gene=MGI:1202064&workUnitName=JAX

See the section <<#_get_all_projects_using_filters>> for an example of a request that uses a filter.

This is the list of filters you can use:

.Filters for projects
|===
|Filter name | Description

|tpn
|TPN(s) to be used as a filter. Eg: TPN:000000013.

|intention
a|Name of the intention. Possible values:

- Point Mutation
- Deletion
- Exon Deletion
- Intra-exon deletion
- Inter-exon deletion
- Whole-gene deletion
- Copy Number Variant
- SNP
- Insertion
- Inverted insertion
- Inversion
- Indel
- Complex rearrangement

|gene
|Marker symbol or accession id(s). Eg.Vps37a,MGI:1261835

|workUnitName
|Name of the work unit(s) associated with any of the plans in the project.

|workGroupName
|Name of the work group(s) associated with any of the plans in the project.

|assignmentStatusName
a|Assignment Status Name. Possible values:

* Assigned
* Inspect - Conflict
* Inactive
* Abandoned
* Inspect - Attempt
* Inspect - GLT Mouse

|summaryStatusName
|Summary Status of the project. Eg: Plan Created.

|colonyName
|Colony name from production plan.

|phenotypingExternalRef
|Specimen or colony name in a phenotyping plan.

|privacyName
|The privacy of the project. Any of: public, protected, restricted.

|imitsMiPlanId
|Ids in iMits (if the project was migrated from iMits).

|===

=== GET
==== Get a specific project

To obtain information about a specific project in the system you can use the TPN identifier to make a request like the one below.

===== Example Request

Curl:
include::{snippets}/projects/getProject/curl-request.adoc[]

===== Example Response

include::{snippets}/projects/getProject/http-response.adoc[]


==== Get all Projects
You can obtain all the projects that the user has permission to view using the following request.
The response is paged, and by default a maximum of 20 results are returned.

===== Example Request

Curl:
include::{snippets}/projects/allProjects/curl-request.adoc[]

===== Example Response

include::{snippets}/projects/allProjects/http-response.adoc[]


[#_get_all_projects_using_filters]
==== Get all Projects using filters.

You can also apply filters to the endpoint to refine the search.Each filter admits several values separated by comma.
The filters you can use are listed above under the section <<#_project_filters>>.


===== Example Request

Curl:
include::{snippets}/projects/allProjectsWithFilter/http-request.adoc[]

===== Example Response

include::{snippets}/projects/allProjectsWithFilter/http-response.adoc[]

=== POST

==== Create a project

In order to create a project, it is necessary to create at least one plan that is attached
to it (palnDetails object).
Tne intention(s) of the project are defined in the creation. It can be a gene and one or
more sequences. The complete set of fields used in the creation are the following:

Fields in project creation:
include::{snippets}/projects/postProject/request-fields.adoc[]

===== Example Request

Curl:
include::{snippets}/projects/postProject/http-request.adoc[]

===== Example Response

include::{snippets}/projects/postProject/http-response.adoc[]

===== Fields in Response
include::{snippets}/projects/postProject/response-fields.adoc[]

=== PUT

==== Update a project

You can update some information in a project if you are related with any of the
work units specified in the plans of the project.

===== Example Request

Curl:
include::{snippets}/projects/putProject/http-request.adoc[]

===== Example Response

include::{snippets}/projects/putProject/http-response.adoc[]

===== Fields in Response
include::{snippets}/projects/putProject/response-fields.adoc[]

== Plans
anchor:chapter-configure[]
This section describes the REST endpoints for plans in the system.

=== Fields
These are the fields you are going to see in the body of a request in a GET or in the payload for POST or PUT
operations.

==== CRISPR plan.
include::{snippets}/plans/getCrisprPlan/response-fields.adoc[]

==== ES Cell plan.
include::{snippets}/plans/getEsCellPlan/response-fields.adoc[]

==== ES Cell Allele Modification plan.
include::{snippets}/plans/getEsCellAlleleModificationPlan/response-fields.adoc[]

==== Phenotyping plan.
include::{snippets}/plans/getPhenotypingPlan/response-fields.adoc[]

=== Filters
When you use the endpoint to get all the plans, you can use filters in a similar way to project filters, see <<Filters>>, to select the information you require.

This is the list of filters you can use:

==== Common filters

.Common filters for plans
|===
|Filter name | Description

|pin
|PIN(s) to be used as a filter. Eg: PIN:0000000014.

|tpn
|TPN(s) to be used as a filter. Eg: TPN:000000001.

|workUnitName
|Name of the work unit associated with the plan.

|workGroup
|Name of the work group associated with the plan.

|summaryStatusName
|Name of the summary status in the plan.

|typeName a|Name of the type of the plan. Possible values are:

* production
* phenotyping

|===

==== Specific filters for production plan

.Filters for production plans
|===
|attemptTypeName a|Attempt type. Possible values are:

* crispr
* haplo-essential crispr
* es cell
* es cell allele modification
* breeding

|imitsMiAttemptId
|iMits mi attempt id.

|===

==== Specific filters for phenotyping plan

.Filters for phenotyping plans
|===
|attemptTypeName a|Attempt type. Possible values are:

* adult and embryo phenotyping
* haplo-essential phenotyping

|imitsPhenotypeAttemptId
|iMits phenotyping attempt id.

|phenotypingExternalRef
|Phentoyping External Reference (colony name or specimen group name).

|doNotCountTowardsCompleteness
|Do not count towards completeness boolean, true or false.

|===

=== GET
==== Get a specific plan

This endpoint shows a plan in the system.

===== Example Request

Curl:
include::{snippets}/plans/getCrisprPlan/curl-request.adoc[]

===== Example Response

include::{snippets}/plans/getCrisprPlan/http-response.adoc[]

==== Get all Plans
This endpoint shows all the plans the user has permission to see.

===== Example Request

Curl:
include::{snippets}/plans/allPlans/curl-request.adoc[]

===== Example Response

include::{snippets}/plans/allPlans/http-response.adoc[]

==== Get filtered Plans
You can also add filters to the request to get more specific results.

===== Example Request

Curl:
include::{snippets}/plans/filteredPlans/curl-request.adoc[]

===== Example Response

include::{snippets}/plans/filteredPlans/http-response.adoc[]

==== Get the history of changes for a plan

You can use this endpoint to see all the changes that have been made on a plan.

===== Example Request

Curl:
include::{snippets}/plans/history/curl-request.adoc[]

===== Example Response

include::{snippets}/plans/history/http-response.adoc[]

=== POST

==== Create a CRISPR plan

===== Example Request

Curl:
include::{snippets}/plans/postCrisprPlan/http-request.adoc[]

===== Example Response

include::{snippets}/plans/postCrisprPlan/http-response.adoc[]

==== Create an ES Cell plan

===== Example Request

Curl:
include::{snippets}/plans/postEsCellPlan/http-request.adoc[]

===== Example Response
include::{snippets}/plans/postEsCellPlan/http-response.adoc[]

==== Create an ES Cell Allele Modification plan

===== Example Request

Curl:
include::{snippets}/plans/postEsCellAlleleModificationPlan/http-request.adoc[]

===== Example Response
include::{snippets}/plans/postEsCellAlleleModificationPlan/http-response.adoc[]

==== Create a Phenotyping plan

===== Example Request

Curl:
include::{snippets}/plans/postPhenotypingPlan/http-request.adoc[]

===== Example Response
include::{snippets}/plans/postPhenotypingPlan/http-response.adoc[]


=== PUT

You can update some information in a plan if you as a user are related to any of the
work units associated with the plan.

The only fields that can be modified are the ones shown in "Example Request". The exception are
pin and tpn, which are there just as a reference to the object that is being modified (they are not
mandatory).

If a value is provided for pin, the system will validate that it matches the pin in the URL parameter.

==== Update a CRISPR plan

===== Example Request

Curl:
include::{snippets}/plans/putCrisprPlan/http-request.adoc[]

===== Example Response

include::{snippets}/plans/putCrisprPlan/http-response.adoc[]

==== Update a ES Cell plan

===== Example Request

Curl:
include::{snippets}/plans/putEsCellPlan/http-request.adoc[]

===== Example Response

include::{snippets}/plans/putEsCellPlan/http-response.adoc[]

==== Update a ES Cell allele modification plan

===== Example Request

Curl:
include::{snippets}/plans/putEsCellAlleleModificationPlan/http-request.adoc[]

===== Example Response

include::{snippets}/plans/putEsCellAlleleModificationPlan/http-response.adoc[]


==== Update a phenotyping plan

===== Example Request

Curl:

include::{snippets}/plans/putPhenotypingPlan/http-request.adoc[]

===== Example Response

include::{snippets}/plans/putPhenotypingPlan/http-response.adoc[]


== Outcomes
anchor:outcomes[]
This section describes the REST endpoints for outcomes in the system.

[TODO:DEFINITION]

An outcome can be either a colony or a specimen.

=== Fields
These are the fields you are going to see in the body of a request in a GET or in the payload for POST or PUT
operations.

==== Colony
include::{snippets}/outcomes/colonyOutcome/response-fields.adoc[]

==== Specimen
include::{snippets}/outcomes/specimenOutcome/response-fields.adoc[]


=== GET
==== Get a specific outcome (Colony)

This endpoint a specific outcome belonging to a plan. In this example the outcome is a colony.

===== Example Request

Curl:
include::{snippets}/outcomes/colonyOutcome/curl-request.adoc[]

===== Example Response

include::{snippets}/outcomes/colonyOutcome/http-response.adoc[]


==== Get a specific outcome (Specimen)

This endpoint a specific outcome belonging to a plan. In this example the outcome is a colony.

===== Example Request

Curl:
include::{snippets}/outcomes/specimenOutcome/curl-request.adoc[]

===== Example Response

include::{snippets}/outcomes/specimenOutcome/http-response.adoc[]


==== Get all outcomes in a plan
This endpoint shows all the outcomes associated to a plan.

===== Example Request

Curl:
include::{snippets}/outcomes/allOutcomes/curl-request.adoc[]

===== Example Response

include::{snippets}/outcomes/allOutcomes/http-response.adoc[]

==== Get the history of changes for an outcome

You can use this endpoint to see all the changes that have been made on an outcome.

===== Example Request

Curl:
include::{snippets}/outcomes/colonyOutcome/history/curl-request.adoc[]

===== Example Response

include::{snippets}/outcomes/colonyOutcome/history/http-response.adoc[]


=== POST

==== Create an outcome (colony)

===== Example Request

Curl:
include::{snippets}/outcomes/postColonyOutcome/http-request.adoc[]

===== Example Response

include::{snippets}/outcomes/postColonyOutcome/http-response.adoc[]

=== PUT

==== Update an outcome (colony)


===== Example Request

Curl:
include::{snippets}/outcomes/putColonyOutcome/http-request.adoc[]

===== Example Response

include::{snippets}/outcomes/putColonyOutcome/http-response.adoc[]


== Mutations
anchor:mutations[]
This section describes the REST endpoints for mutations in the system.

=== Fields
These are the fields you are going to see in the body of a request in a GET or in the payload for POST or PUT
operations.
include::{snippets}/mutations/mutation/response-fields.adoc[]

=== GET
==== Get a specific mutation

This endpoint fetches a specific mutation associated with an outcome.

===== Example Request

Curl:
include::{snippets}/mutations/mutation/curl-request.adoc[]

===== Example Response

include::{snippets}/mutations/mutation/http-response.adoc[]

==== Get history for a specific mutation

This endpoint fetches the history of a specific mutation associated with an outcome.

===== Example Request

Curl:
include::{snippets}/mutations/mutation/history/curl-request.adoc[]

===== Example Response

include::{snippets}/mutations/mutation/history/http-response.adoc[]

=== POST
A mutation is created as part of an outcome, see <<Create an outcome (colony)>>, rather than as a POST request to a mutation endpoint.

=== PUT
==== Update a mutation

This endpoint allows the modification of an existing mutation.

===== Example Request

Curl:
include::{snippets}/mutations/mutation/putMutation/curl-request.adoc[]

===== Example Response

include::{snippets}/mutations/mutation/putMutation/http-response.adoc[]



== Phenotyping Stages
anchor:phenotypingStages[]
This section describes the REST endpoints for phenotyping stages in the system.

[TODO:DEFINITION]

=== Fields
These are the fields you are going to see in the body of a request in a GET or in the payload for POST or PUT
operations.

include::{snippets}/phenotypingStages/getPhenotypingStage/response-fields.adoc[]


=== GET
==== Get a specific phenotyping stage

This endpoint fetches a specific phenotyping stage belonging to a plan.

===== Example Request

Curl:
include::{snippets}/phenotypingStages/getPhenotypingStage/curl-request.adoc[]

===== Example Response

include::{snippets}/phenotypingStages/getPhenotypingStage/http-response.adoc[]


==== Get all phenotyping stages in a plan
This endpoint shows all the phenotyping stages associated to a plan.

===== Example Request

Curl:
include::{snippets}/phenotypingStages/allPhenotypingStages/curl-request.adoc[]

===== Example Response

include::{snippets}/phenotypingStages/allPhenotypingStages/http-response.adoc[]

==== Get the history of changes for a phenotyping stage

You can use this endpoint to see all the changes that have been made on a phenotyping stage.

===== Example Request

Curl:
include::{snippets}/phenotypingStages/history/curl-request.adoc[]

===== Example Response

include::{snippets}/phenotypingStages/history/http-response.adoc[]


=== POST

==== Create a phenotyping stage

===== Example Request

Curl:
include::{snippets}/phenotypingStages/postPhenotypingStage/http-request.adoc[]

===== Example Response
include::{snippets}/phenotypingStages/postPhenotypingStage/http-response.adoc[]


=== PUT

==== Update a phenotyping stage

===== Example Request

Curl:
include::{snippets}/phenotypingStages/putPhenotypingStage/http-request.adoc[]

===== Example Response
include::{snippets}/phenotypingStages/putPhenotypingStage/http-response.adoc[]


== State Machine interaction

=== Structure

Several entities in GenTaR rely on a state machine to control the logic to change from one status
to another. The state machines for these entities are described in the following document.

link:state_machine_transitions.pdf[state_machine_transitions.pdf]

When you make a GET request to one of those entities, as part of the response you will receive a *statusTransition*
section, which contains information about the current status and what actions can be executed in order
to change that status.

```json
"statusTransition" : {
    "currentStatus" : "Founder Obtained",
    "transitions" : [ {
    "action" : "abortWhenFounderObtained",
    "description" : "Abort the plan after a founder obtained",
    "triggeredByUser" : true,
    "available" : true,
    "note" : null,
    "nextStatus" : "AttemptAborted"
    } ],
    "actionToExecute" : null
```


|===
|Path|Type|Description

|`+statusTransition+`
|`+Object+`
|Information about the current state in the state machine for the plan.

|`+statusTransition.currentStatus+`
|`+String+`
|Current status in the plan

|`+statusTransition.transitions[]+`
|`+Array+`
|Transitions in the state machine given the current state.

|`+statusTransition.transitions[].action+`
|`+String+`
|Action or transition's name.

|`+statusTransition.transitions[].description+`
|`+String+`
|Transition's description.

|`+statusTransition.transitions[].triggeredByUser+`
|`+Boolean+`
|Indicates whether the transition is executed by the user or by the system.

|`+statusTransition.transitions[].available+`
|`+Boolean+`
|Indicates if the transition can be executed at the moment.

|`+statusTransition.transitions[].note+`
|`+Null+`
|Additional explanation about the availability to execute the transition.

|`+statusTransition.transitions[].nextStatus+`
|`+String+`
|Next status that the plan will have if the transition is executed.

|`+statusTransition.actionToExecute+`
|`+Null+`
|Name of the transition (action) to execute.


|===


=== Executing a change in the state machine
To execute a transition in the plan, you need to choose an action that is _triggeredByUser = true_
and _available = true_ and send a PUT request (as a normal plan update ) passing the name of the action
as the value _actionToExecute_ in the statusTransition section of the payload.


==== Example Request

Let's suppose you want to abort a crispr plan that has the status _Founder Obtained_. If we do a _GET_
to the plan we want to abort, you will see the _statusTransition_ section with a single available
transition executable by the user: *abortWhenFounderObtained*.

Use the name of the action (abortWhenFounderObtained) as the value in the field *actionToExecute*.

You can use the whole GET response as the payload for the new operation. You can also decide to send
only the _statusTransition_ information in the payload. The following is an example of a request
where you decide to leave out the attempt information:

Curl:
include::{snippets}/plans/putPlanStateMachine/http-request.adoc[]


==== Example Response

The response will indicate what has changed in the system, along with a link to the resource in
case you need to retrieve the new object.

include::{snippets}/plans/putPlanStateMachine/http-response.adoc[]

== Lastest updates

* 2021-06-25: - Added the field esCellQcOnly to the Project entity to support projects that only relate to ES Cell QC.
              - Added documentation on the fields present in ES cell production plans.
              - Add documentation on the fields present in ES cell allele modification production plans.
              - Updated the state_machine_transitions document.
              - GET requests for ES cell and ES cell allele modification production plans are
                supported on the GenTaR Sandbox test database.
* 2021-02-24: Add two new filters to projects. One for production colony names and one for phenotyping external
              references.
* 2021-01-26: Phenotyping Stage state machine: The rollbackPhenotypingAllDataProcessed action used by the DCC
              now moves the PhenotypingAllDataProcessed state to PhenotypingAllDataSent rather than
              PhenotypingStarted.
* 2020-11-30: New filter 'doNotCountTowardsCompleteness' added for phenotyping plans.
* 2021-10-04: The 'species' field have been removed from project object.
* 2021-10-04: The 'funders' field in plans can be updated after plan created.
* 2021-10-04: The creAlleleModificationAttempt object have been *renamed* to eSCellAlleleModificationAttempt.
* 2021-10-04: Two *legacy* fields have been added to the esCellAlleleModificationAttempt object: 'imitsMouseAlleleModId' and
              'imitsTargRepAlleleId'. They will be read_only and only be there is the data was migrated from iMits.
* 2021-10-04: Three *legacy* fields have been added to the phenotypingAttemptResponse object: 'imitsPhenotypeAttemptId',
              'imitsPhenotypingProductionId' and 'imitsParentColonyId'. They will be read_only and only be there is the data was migrated from iMits.
* 2021-10-04: The *legacy* field 'imitsAllele' in mutation object has been renamed to 'imitsAlleleId' for consistency.
              It will be read_only and only be there is the data was migrated from iMits.

